In [1]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

c = np.concatenate((a,b),axis = 0)
print(c)

[1 2 3 4 5 6]


In [6]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[12,13,14],[23,24,25]])
c = np.concatenate((a,b),axis=1)
print("c:",c)
d = np.concatenate((a,b),axis=0)
print("d:",d)

c: [[ 1  2  3 12 13 14]
 [ 4  5  6 23 24 25]]
d: [[ 1  2  3]
 [ 4  5  6]
 [12 13 14]
 [23 24 25]]


In [7]:
import numpy as np

a = np.arange(9)
print(a)
res = np.split(a,3)
print(res)

[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [10]:
import numpy as np

a = np.arange(9)
print(a)
res = np.split(a,3)
print(res)

for i,arr in enumerate(res):
    print("splited array",i+1)
    print(arr)


[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
splited array 1
[0 1 2]
splited array 2
[3 4 5]
splited array 3
[6 7 8]


In [14]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(np.resize(a,(2,3)))

(2, 3)
[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(np.append(a,[9,56,89])) #????????

[[1 2 3]
 [4 5 6]]
[ 1  2  3  4  5  6  9 56 89]


In [2]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(np.append(a,[[9,56,89],[34,565,87]],axis=1))

[[1 2 3]
 [4 5 6]]
[[  1   2   3   9  56  89]
 [  4   5   6  34 565  87]]


In [23]:
import numpy as np

a = np.array([[1,2],[3,4],[5,6]])
print(a)
print(np.insert(a,3,[87,89]))

[[1 2]
 [3 4]
 [5 6]]
[ 1  2  3 87 89  4  5  6]


In [9]:
import numpy as np
a = np.arange(15)
np.random.shuffle(a) 
a.reshape(3,5)
print(a)

[ 4  1 12  2  6  3 14  9  5 13 10  8  7  0 11]


In [43]:
import numpy as np
a = np.arange(15).reshape(3,5)
print(a)

print(np.delete(a,6))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[ 0  1  2  3  4  5  7  8  9 10 11 12 13 14]


In [30]:
import numpy as np
a = np.arange(15)
res = np.flip(a)
print(res)

[14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [33]:
import numpy as np

a= np.array([25,5,15,10])
a= np.sort(a)
print(a)

[ 5 10 15 25]


In [36]:
import numpy as np

a= np.array([25,5,15,10])
max = np.argmax(a)
print(max)
min = np.argmin(a)
print(min)

0
1


In [37]:
import numpy as np
a = np.arange(10)
res = a[4::]
print(res)

[4 5 6 7 8 9]


In [40]:
import numpy as np
a = np.arange(10)
res = a[-1::-1]
print(res)

[9 8 7 6 5 4 3 2 1 0]


In [47]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
print(a.shape)

a.shape = (2,3)
print(a)

(3, 2)
[[1 2 3]
 [4 5 6]]


In [50]:
import numpy as np

a = np.arange(24)
a.ndim
print(a)
res = a.reshape(2,3,4)
print(res)
print(a.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
24


In [ ]:
import numpy as np

a= np.array([25,5,15,10],dtype = np.int32)
print(a, a.dtype)

[25  5 15 10] int32


In [52]:
import numpy as np
a = np.array([11,12,13])
b = np.array([22,33,44])
print(a%b)

[11 12 13]


In [55]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[11,22,33],[44,55,66]])
print(a+b)
print(a%b)
print(a**b)

[[12 24 36]
 [48 60 72]]
[[1 2 3]
 [4 5 6]]
[[                1           4194304  5559060566555523]
 [                0 -3178808521666707                 0]]


In [58]:
import numpy as np
b = np.array([[11,22,33],[44,55,66]])

res = np.sum(a,axis=1)
print(a)
print(res)

[[1 2 3]
 [4 5 6]]
[ 6 15]


In [59]:
import numpy as np
b = np.array([[11,22,33],[44,55,66]])

res = np.mean(a,axis=1)
print(a)
print(res)

[[1 2 3]
 [4 5 6]]
[2. 5.]


In [66]:
import numpy as np
b = np.array([3.4j,2.8j,6., 1+3j])
print(np.real(b))
print(np.imag(b))
print(np.conj(b))
print(np.angle(b,deg = True))

[0. 0. 6. 1.]
[3.4 2.8 0.  3. ]
[0.-3.4j 0.-2.8j 6.-0.j  1.-3.j ]
[90.         90.          0.         71.56505118]
