In [1]:
import numpy as np

a = np.random.rand(3,4)
print(a)



[[0.26753308 0.52103486 0.24105915 0.31522117]
 [0.47958863 0.83933871 0.34826586 0.37835781]
 [0.41809545 0.69996303 0.41444321 0.70384398]]


In [2]:
import numpy as np

a = np.empty((3,4))
print(a)

[[0.26753308 0.52103486 0.24105915 0.31522117]
 [0.47958863 0.83933871 0.34826586 0.37835781]
 [0.41809545 0.69996303 0.41444321 0.70384398]]


In [5]:
import numpy as np

a = np.full((3,4),6)
print(a)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [7]:
import numpy as np

a = np.array([1,2,3,4,5])
print(a[2])

print(a[2]+a[4])

3
8


In [9]:
import numpy as np

a = np.array([[1,2,3,4,5],
             [6,7,8,9,10]])
print(a[1,2])

8


In [16]:
import numpy as np

a = np.array([
    [[1,2,3,4,5],
    [6,7,8,9,10]],
             [[23,34,45,56,76],
             [12,14,15,16,17]]])
print(a[1,1,3])

16


In [17]:
import numpy as np

a = np.array([
    [[1,2,3,4,5],
    [6,7,8,9,10]],
             [[23,34,45,56,76],
             [12,14,15,16,17]]])
print(a[1,1,-1])

17


In [ ]:
#slicing in python for array
import numpy as np

a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a[0:5:2]) #[start:end:step]

[1 3 5]


In [21]:
import numpy as np
a = np.array(
    [[1,2,3,4,5],
    [6,7,8,9,10]])
print(a[0:3,2:4])

[[3 4]
 [8 9]]


In [30]:
import numpy as np
a =np.array([
    [[1,2,3,4,5],[6,7,8,9,10]],
    [[23,34,45,56,76],[12,14,15,16,17]]])
print(a.shape)
print(a[1,1,3])

a = np.full((3,4,5),3)
print(a)

(2, 2, 5)
16
[[[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]]


In [31]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8,9,10])
x = a.copy()
a[0]=50
print(a)
print(x)

[50  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [32]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8,9,10])
x = a.view()
a[0]=50
print(a)
print(x)

[50  2  3  4  5  6  7  8  9 10]
[50  2  3  4  5  6  7  8  9 10]


In [33]:
import numpy as np

a = np.array(
    [[1,2,3,4,5],
    [6,7,8,9,10]])

print(a.shape)

(2, 5)
