In [ ]:
import pandas as pd
df=pd.read_csv('customers-100.csv')
print(df)

res=df.groupby('Country')
print(res)

pd.options.display.max_rows=100  # defining the number of rows to display
#print(df)
print(df.head(10))  # print top rows
print(df.tail(10))  # print bottom rows

print(df.shape)  # gives the total rows and columns in the dataframe

print(df.columns) # gives all the columns

# printing specific columns from the ddata frame
print(df['Country'].head(5))

# printing rows based on condition
print(df[df['Country']=='Bulgaria'])
print(df[df['Subscription Date']=='2020-08-24'])

print(df[df['Country']=='Sri Lanka'].value_counts())

# filling missing values
df.fillna({'Country': '-','City':'-'},inplace=True)
print(df)

# to replace with agg value
# x=df['column'].agg_func()
# df.fillna({'column_name':'x'},inplace=True)  inplace--apply the changes to original data frame 





    Index      Customer Id First Name Last Name  \
0       1  DD37Cf93aecA6Dc     Sheryl    Baxter   
1       2  1Ef7b82A4CAAD10    Preston    Lozano   
2       3  6F94879bDAfE5a6        Roy     Berry   
3       4  5Cef8BFA16c5e3c      Linda     Olsen   
4       5  053d585Ab6b3159     Joanna    Bender   
..    ...              ...        ...       ...   
95     96  cb8E23e48d22Eae       Karl     Greer   
96     97  CeD220bdAaCfaDf       Lynn  Atkinson   
97     98  28CDbC0dFe4b1Db       Fred    Guerra   
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer   
99    100  2354a0E336A91A1   Clarence    Haynes   

                            Company               City  \
0                   Rasmussen Group       East Leonard   
1                       Vega-Gentry  East Jimmychester   
2                     Murillo-Perry      Isabelborough   
3   Dominguez, Mcmillan and Donovan         Bensonview   
4          Martin, Lang and Andrade     West Priscilla   
..                              ...    

In [ ]:
# date time function in python
# date_range -- generate sequence of dates
import pandas as pd
print(pd.date_range('05-28-2026',periods=5))



DatetimeIndex(['2026-05-28', '2026-05-29', '2026-05-30', '2026-05-31',
               '2026-06-01'],
              dtype='datetime64[us]', freq='D')


In [12]:
# loading json file in a data frame
import pandas as pd
df=pd.read_json('C:/Users/jyoti agrawal/Downloads/user-complete-profile.json')
print(df)

               userId            name                email         address  \
street           1001  Sarah Williams  sarah.w@example.com  456 Oak Avenue   
city             1001  Sarah Williams  sarah.w@example.com        Portland   
state            1001  Sarah Williams  sarah.w@example.com              OR   
zipCode          1001  Sarah Williams  sarah.w@example.com           97201   
country          1001  Sarah Williams  sarah.w@example.com             USA   
home             1001  Sarah Williams  sarah.w@example.com             NaN   
mobile           1001  Sarah Williams  sarah.w@example.com             NaN   
newsletter       1001  Sarah Williams  sarah.w@example.com             NaN   
notifications    1001  Sarah Williams  sarah.w@example.com             NaN   
language         1001  Sarah Williams  sarah.w@example.com             NaN   

                         phone preferences  
street                     NaN         NaN  
city                       NaN         NaN  
state 

In [3]:
# NumPy in python--Numerical Python
import numpy as np
print(np.__version__)

# 1_D array in numpy
a=np.array([1,2,3,4,4])
print(a,type(a),a.dtype)

# 2-D array in numpy
a=np.array([[1,2],[3,4],[5,6]])
print("\n",a)

b=np.array(['ab','b','c'])  #U(n)-unicode(length) 
print(b,type(b),b.dtype)

# zero array
print(np.zeros(4)) # 1-D
print(np.zeros((3,4))) # 2-D

# array of ones
print("\n",np.ones((2,3)))

# Fortron ordered array of ones- columns are major and rows are minor
print("\n",np.ones((3,5),order='F'))

print("\n",np.arange(5,50,5))  # gives an array of specific range(start,end-not included,interval)

print(np.linspace(1,10))





2.4.6
[1 2 3 4 4] <class 'numpy.ndarray'> int64

 [[1 2]
 [3 4]
 [5 6]]
['ab' 'b' 'c'] <class 'numpy.ndarray'> <U2
[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 [[1. 1. 1.]
 [1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 [ 5 10 15 20 25 30 35 40 45]
[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
